{
 "title": "oncall-dashboard",
 "time": { "from": "2025-11-23T16:00:00.000Z", "to": "2025-11-23T17:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "pql label_values(kube_pod_container_status_last_terminated_reason{namespace=\"st-ab1-fadeev\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "SLO, Pod статусы & Использование ресурсов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Готовность контейнеров",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "kube_pod_container_status_ready{namespace=\"st-ab1-fadeev\",container=~\"oncall|mysql\"}",
     "legendFormat": "{{namespace}}/{{container}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "SLA сервиса",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "avg(last_over_time(sla_percent{group=\"ab1_fadeev\"}[10m]))\n",
     "size": 100000
    }
   ]
  },
  {
   "title": "SLA сервиса",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "last_over_time(sla_percent{group=\"ab1_fadeev\"}[10m])",
     "size": 100000
    }
   ]
  },
  {
   "title": "Использование CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "step=1m (\n  100 *\n  sum(\n      rate(container_cpu_usage_seconds_total{\n          namespace=\"st-ab1-fadeev\",\n          container=~\"oncall|mysql\",\n          env=~\"prod\",\n      }[5m])\n  ) by (pod, container) /\n  sum(\n      kube_pod_container_resource_requests{\n          namespace=\"st-ab1-fadeev\",\n          container=~\"oncall|mysql\",\n          env=~\"prod\",\n          resource=\"cpu\",\n      }\n  ) by (pod, container)\n)\n",
     "legendFormat": "{{container}} in {{pod}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Использование RAM (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{image!=\"\", namespace=\"st-ab1-fadeev\", container=~\"oncall|mysql\"}) by (pod, container)\n      /\n    sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"st-ab1-fadeev\", container=~\"oncall|mysql\"} > 0) by (pod, container)\n)",
     "legendFormat": "{{container}} in {{pod}}",
     "size": 100000
    }
   ]
  },
  { "title": "Lifetime контейнеров & пробы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Статусы контейнеров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "last_over_time(kube_pod_container_status_ready{namespace=\"st-ab1-fadeev\",container=~\"oncall|mysql\"})[10m:]",
     "legendFormat": "{{container}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "P99-latency проб",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "last_over_time(\n  histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        probe_request_duration_seconds_bucket{\n          group=\"ab1_fadeev\",\n          service=\"oncall-prober\",\n        }[10m]\n      )\n    ) by (le, target)\n  )[10m:]\n)\n",
     "legendFormat": "latency {{target}}",
     "size": 100000
    }
   ]
  },
  {
   "title": "Статистика проб",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "(1 - (\n    sum(rate(probe_request_errors_total{group=\"ab1_fadeev\", service=\"oncall-prober\", target=\"http://oncall:8080/healthcheck\"}[10m])) by (service, group, target)\n    /\n    sum(rate(probe_requests_total{group=\"ab1_fadeev\", service=\"oncall-prober\", target=\"http://oncall:8080/healthcheck\"}[10m])) by (service, group, target)\n)) * 100\n",
     "legendFormat": "Процент успешных обращений к {{target}}",
     "size": 100000
    }
   ]
  },
  { "title": "Ошибки", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Ошибки пода $pod",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "repeat": "pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum by (reason) (\n  kube_pod_container_status_last_terminated_reason{namespace=\"st-ab1-fadeev\", pod=~\"$pod\"}\n)",
     "size": 100000
    }
   ]
  },
  {
   "title": "Количество рестартов подов",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "chart": "prefix",
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"st-ab1-fadeev\"})[15d:]",
     "legendFormat": "{{pod}}",
     "size": 100000
    }
   ]
  }
 ]
}